//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EntityInheritance_MT
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EntityInheritanceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EntityInheritanceEntities object using the connection string found in the 'EntityInheritanceEntities' section of the application configuration file.
        /// </summary>
        public EntityInheritanceEntities() : base("name=EntityInheritanceEntities", "EntityInheritanceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntityInheritanceEntities object.
        /// </summary>
        public EntityInheritanceEntities(string connectionString) : base(connectionString, "EntityInheritanceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntityInheritanceEntities object.
        /// </summary>
        public EntityInheritanceEntities(EntityConnection connection) : base(connection, "EntityInheritanceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Login> Logins
        {
            get
            {
                if ((_Logins == null))
                {
                    _Logins = base.CreateObjectSet<Login>("Logins");
                }
                return _Logins;
            }
        }
        private ObjectSet<Login> _Logins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<Person>("People");
                }
                return _People;
            }
        }
        private ObjectSet<Person> _People;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Logins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogins(Login login)
        {
            base.AddObject("Logins", login);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityInheritanceModel", Name="Client")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Client : Person
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="createdDtTm">Initial value of the CreatedDtTm property.</param>
        /// <param name="modifiedDtTm">Initial value of the ModifiedDtTm property.</param>
        public static Client CreateClient(global::System.Int64 id, global::System.String name, global::System.DateTime createdDtTm, global::System.DateTime modifiedDtTm)
        {
            Client client = new Client();
            client.Id = id;
            client.Name = name;
            client.CreatedDtTm = createdDtTm;
            client.ModifiedDtTm = modifiedDtTm;
            return client;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreditPeriod
        {
            get
            {
                return _CreditPeriod;
            }
            set
            {
                OnCreditPeriodChanging(value);
                ReportPropertyChanging("CreditPeriod");
                _CreditPeriod = StructuralObject.SetValidValue(value, true, "CreditPeriod");
                ReportPropertyChanged("CreditPeriod");
                OnCreditPeriodChanged();
            }
        }
        private global::System.String _CreditPeriod;
        partial void OnCreditPeriodChanging(global::System.String value);
        partial void OnCreditPeriodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CreditLimit
        {
            get
            {
                return _CreditLimit;
            }
            set
            {
                OnCreditLimitChanging(value);
                ReportPropertyChanging("CreditLimit");
                _CreditLimit = StructuralObject.SetValidValue(value, "CreditLimit");
                ReportPropertyChanged("CreditLimit");
                OnCreditLimitChanged();
            }
        }
        private Nullable<global::System.Decimal> _CreditLimit;
        partial void OnCreditLimitChanging(Nullable<global::System.Decimal> value);
        partial void OnCreditLimitChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityInheritanceModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : Person
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="createdDtTm">Initial value of the CreatedDtTm property.</param>
        /// <param name="modifiedDtTm">Initial value of the ModifiedDtTm property.</param>
        public static Employee CreateEmployee(global::System.Int64 id, global::System.String name, global::System.DateTime createdDtTm, global::System.DateTime modifiedDtTm)
        {
            Employee employee = new Employee();
            employee.Id = id;
            employee.Name = name;
            employee.CreatedDtTm = createdDtTm;
            employee.ModifiedDtTm = modifiedDtTm;
            return employee;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Salary
        {
            get
            {
                return _Salary;
            }
            set
            {
                OnSalaryChanging(value);
                ReportPropertyChanging("Salary");
                _Salary = StructuralObject.SetValidValue(value, "Salary");
                ReportPropertyChanged("Salary");
                OnSalaryChanged();
            }
        }
        private Nullable<global::System.Decimal> _Salary;
        partial void OnSalaryChanging(Nullable<global::System.Decimal> value);
        partial void OnSalaryChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityInheritanceModel", Name="Login")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Login : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Login object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static Login CreateLogin(global::System.Int64 id, global::System.String name, global::System.String userName, global::System.String password)
        {
            Login login = new Login();
            login.Id = id;
            login.Name = name;
            login.UserName = userName;
            login.Password = password;
            return login;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false, "UserName");
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityInheritanceModel", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Client))]
    [KnownTypeAttribute(typeof(Employee))]
    [KnownTypeAttribute(typeof(Vendor))]
    public partial class Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="createdDtTm">Initial value of the CreatedDtTm property.</param>
        /// <param name="modifiedDtTm">Initial value of the ModifiedDtTm property.</param>
        public static Person CreatePerson(global::System.Int64 id, global::System.String name, global::System.DateTime createdDtTm, global::System.DateTime modifiedDtTm)
        {
            Person person = new Person();
            person.Id = id;
            person.Name = name;
            person.CreatedDtTm = createdDtTm;
            person.ModifiedDtTm = modifiedDtTm;
            return person;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNo
        {
            get
            {
                return _PhoneNo;
            }
            set
            {
                OnPhoneNoChanging(value);
                ReportPropertyChanging("PhoneNo");
                _PhoneNo = StructuralObject.SetValidValue(value, true, "PhoneNo");
                ReportPropertyChanged("PhoneNo");
                OnPhoneNoChanged();
            }
        }
        private global::System.String _PhoneNo;
        partial void OnPhoneNoChanging(global::System.String value);
        partial void OnPhoneNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailId
        {
            get
            {
                return _EmailId;
            }
            set
            {
                OnEmailIdChanging(value);
                ReportPropertyChanging("EmailId");
                _EmailId = StructuralObject.SetValidValue(value, true, "EmailId");
                ReportPropertyChanged("EmailId");
                OnEmailIdChanged();
            }
        }
        private global::System.String _EmailId;
        partial void OnEmailIdChanging(global::System.String value);
        partial void OnEmailIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDtTm
        {
            get
            {
                return _CreatedDtTm;
            }
            set
            {
                OnCreatedDtTmChanging(value);
                ReportPropertyChanging("CreatedDtTm");
                _CreatedDtTm = StructuralObject.SetValidValue(value, "CreatedDtTm");
                ReportPropertyChanged("CreatedDtTm");
                OnCreatedDtTmChanged();
            }
        }
        private global::System.DateTime _CreatedDtTm;
        partial void OnCreatedDtTmChanging(global::System.DateTime value);
        partial void OnCreatedDtTmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDtTm
        {
            get
            {
                return _ModifiedDtTm;
            }
            set
            {
                OnModifiedDtTmChanging(value);
                ReportPropertyChanging("ModifiedDtTm");
                _ModifiedDtTm = StructuralObject.SetValidValue(value, "ModifiedDtTm");
                ReportPropertyChanged("ModifiedDtTm");
                OnModifiedDtTmChanged();
            }
        }
        private global::System.DateTime _ModifiedDtTm;
        partial void OnModifiedDtTmChanging(global::System.DateTime value);
        partial void OnModifiedDtTmChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityInheritanceModel", Name="Vendor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vendor : Person
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vendor object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="createdDtTm">Initial value of the CreatedDtTm property.</param>
        /// <param name="modifiedDtTm">Initial value of the ModifiedDtTm property.</param>
        public static Vendor CreateVendor(global::System.Int64 id, global::System.String name, global::System.DateTime createdDtTm, global::System.DateTime modifiedDtTm)
        {
            Vendor vendor = new Vendor();
            vendor.Id = id;
            vendor.Name = name;
            vendor.CreatedDtTm = createdDtTm;
            vendor.ModifiedDtTm = modifiedDtTm;
            return vendor;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreditPeriod
        {
            get
            {
                return _CreditPeriod;
            }
            set
            {
                OnCreditPeriodChanging(value);
                ReportPropertyChanging("CreditPeriod");
                _CreditPeriod = StructuralObject.SetValidValue(value, true, "CreditPeriod");
                ReportPropertyChanged("CreditPeriod");
                OnCreditPeriodChanged();
            }
        }
        private global::System.String _CreditPeriod;
        partial void OnCreditPeriodChanging(global::System.String value);
        partial void OnCreditPeriodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CreditLimit
        {
            get
            {
                return _CreditLimit;
            }
            set
            {
                OnCreditLimitChanging(value);
                ReportPropertyChanging("CreditLimit");
                _CreditLimit = StructuralObject.SetValidValue(value, "CreditLimit");
                ReportPropertyChanged("CreditLimit");
                OnCreditLimitChanged();
            }
        }
        private Nullable<global::System.Decimal> _CreditLimit;
        partial void OnCreditLimitChanging(Nullable<global::System.Decimal> value);
        partial void OnCreditLimitChanged();

        #endregion

    }

    #endregion

}
